### ISSUE TITLE
Unable to authorize with Trakt

### ISSUE THREAD

**Issue by baltzis** [Ezra-Hubbard/Ezra-Hubbard.github.io#45]
A very long error message keeps popping up each time I try to authorize Ezra with Trakt using MyAccounts. The window displaying the code to authorize does not appear and the error message refers to some api (api-V2launch.trakt.tv).

**Comment by rostifer72** [comment]
This error has been happening over two weeks now for me. Even when I try and use my own Trakt api keys.

**Comment by Ezra-Hubbard** [comment]
Fixed with https://github.com/Ezra-Hubbard/script.module.myaccounts/pull/5 (hopefully)

**Comment by DPAmes** [comment]
Still unable to authorize with Trakt at the new api address with the latest My Accounts 2.1.1 from the Ezra repository. Error message from the log before attempting to re-authorize is: ###Trakt Error###: 401 Client Error: Unauthorized for url: https://api.trakt.tv/sync/last_activities  (My Accounts is still authorized at Trakt)
After removing existing authorization both in My Accounts and at Trakt and trying to re-authorize: no effect, returns silently with no error message from Kodi.

**Comment by Ezra-Hubbard** [comment]
> Still unable to authorize with Trakt at the new api address with the latest My Accounts 2.1.1 from the Ezra repository. Error message from the log before attempting to re-authorize is: ###Trakt Error###: 401 Client Error: Unauthorized for url: https://api.trakt.tv/sync/last_activities (My Accounts is still authorized at Trakt) After removing existing authorization both in My Accounts and at Trakt and trying to re-authorize: no effect, returns silently with no error message from Kodi.

should b e fixed now. 

it was actually fixed in accounts 2.1.2 but, an error in the repo xml meant that the repo did not auto update anyone to 2.1.2 (unless they were lucky enough to update in teh few hours between 2.1.2 being pushed and the repo getting broken :D)

should all work now with latest accounts module
